  const Movies = [
        { name: 'How you dragon', genre: 'Action', ratings: 8.1, status: 'available' },
        { name: 'The Lion roar', genre: 'Animation', ratings: 8.5, status: 'available' },
        { name: 'Interception', genre: 'Sci-Fi', ratings: 8.8, status: 'available' },
        { name: 'Grandfather', genre: 'Crime', ratings: 9.2, status: 'available' },
        { name: 'My redemption', genre: 'Drama', ratings: 9.3, status: 'available' },
        { name: 'The Stale', genre: 'Thriller', ratings: 8.9, status: 'available' },
        { name: 'The moonlight', genre: 'Action', ratings: 9.0, status: 'available' },
        { name: 'mores Gump', genre: 'Drama', ratings: 8.8, status: 'available' },
        { name: 'My name is', genre: 'Sci-Fi', ratings: 8.7, status: 'available' },
        { name: 'Mighty one', genre: 'Drama', ratings: 8.8, status: 'available' },
        { name: 'Manuscer', genre: 'Sci-Fi', ratings: 8.6, status: 'available' },
        { name: 'Bad leadator', genre: 'Action', ratings: 8.5, status: 'available' },
        { name: 'The Science of camp', genre: 'Thriller', ratings: 8.6, status: 'available' },
        { name: 'water mist', genre: 'History', ratings: 9.0, status: 'available' },
        { name: 'Mr retarded', genre: 'Crime', ratings: 8.5, status: 'available' },
        { name: 'The porcha method', genre: 'Drama', ratings: 7.7, status: 'available' },
        { name: 'my eyesight', genre: 'Thriller', ratings: 8.6, status: 'available' },
        { name: 'Land owners', genre: 'Action', ratings: 8.0, status: 'available' },
        { name: 'True story', genre: 'Animation', ratings: 8.3, status: 'available' },
        { name: 'baggind depot', genre: 'Animation', ratings: 8.1, status: 'available' },
        { name: 'manchester', genre: 'Sci-Fi', ratings: 7.8, status: 'available' },
        { name: 'Mr movie star', genre: 'Adventure', ratings: 8.1, status: 'available' },
        { name: 'Catwalk', genre: 'Sci-Fi', ratings: 8.6, status: 'available' },
        { name: 'The unusuall', genre: 'Adventure', ratings: 8.5, status: 'available' },
        { name: 'Talk to me', genre: 'Fantasy', ratings: 8.8, status: 'available' },
        { name: 'Hug to steal', genre: 'Fantasy', ratings: 7.6, status: 'available' },
        { name: 'Mr moskow', genre: 'Fantasy', ratings: 8.0, status: 'available' },
        { name: 'The livid', genre: 'Animation', ratings: 8.0, status: 'available' },
        { name: 'Saxophone lady', genre: 'Animation', ratings: 8.4, status: 'available' },
        { name: 'Nobo', genre: 'Animation', ratings: 8.4, status: 'available' },    
        { name: 'Whoss', genre: 'Animation', ratings: 8.0, status: 'available' },
        { name: 'Monami', genre: 'Animation', ratings: 7.6, status: 'available' },
        { name: 'Boaz journey', genre: 'Animation', ratings: 7.4, status: 'available' },
        { name: 'break', genre: 'Animation', ratings: 7.9, status: 'available' },
        { name: 'Nada', genre: 'Animation', ratings: 7.6, status: 'available' },
        { name: 'Donald', genre: 'Animation', ratings: 7.6, status: 'available' },
        { name: 'Wiskas', genre: 'Animation', ratings: 6.4, status: 'available' },
        { name: 'The Secret', genre: 'Animation', ratings: 6.5, status: 'available' },
        { name: 'The Mrs', genre: 'Comedy', ratings: 8.9, status: 'available' },
        { name: 'Trend', genre: 'Comedy', ratings: 8.9, status: 'available' },
        {name : 'epices movie', genre: 'Comedy', ratings: 2.8, status: 'available'},
        {name : 'Extremese Movie', genre: 'Comedy', ratings: 2.4, status: 'available'},
        {name : 'Disastere Movie', genre: 'Comedy', ratings: 2.0, status: 'available'},
        {name : 'Meet Spart', genre: 'Comedy', ratings: 2.0, status: 'available'},
        {name : 'Super Movie', genre: 'Comedy', ratings: 2.5, status: 'available'}, 
        {name : 'The Starvings', genre: 'Comedy', ratings: 2.0, status: 'available'},
        {name : 'The wango', genre: 'Comedy', ratings: 7.7, status: 'available'},



    ];
export default Movies;