  const Movies = [
        { name: 'How to train your dragon', genre: 'Action', ratings: 8.1, status: 'available' },
        { name: 'The Lion King', genre: 'Animation', ratings: 8.5, status: 'available' },
        { name: 'Inception', genre: 'Sci-Fi', ratings: 8.8, status: 'available' },
        { name: 'The Godfather', genre: 'Crime', ratings: 9.2, status: 'available' },
        { name: 'The Shawshank Redemption', genre: 'Drama', ratings: 9.3, status: 'available' },
        { name: 'Pulp Fiction', genre: 'Thriller', ratings: 8.9, status: 'available' },
        { name: 'The Dark Knight', genre: 'Action', ratings: 9.0, status: 'available' },
        { name: 'Forrest Gump', genre: 'Drama', ratings: 8.8, status: 'available' },
        { name: 'The Matrix', genre: 'Sci-Fi', ratings: 8.7, status: 'available' },
        { name: 'Fight Club', genre: 'Drama', ratings: 8.8, status: 'available' },
        { name: 'Interstellar', genre: 'Sci-Fi', ratings: 8.6, status: 'available' },
        { name: 'Gladiator', genre: 'Action', ratings: 8.5, status: 'available' },
        { name: 'The Silence of the Lambs', genre: 'Thriller', ratings: 8.6, status: 'available' },
        { name: 'Schindler\'s List', genre: 'History', ratings: 9.0, status: 'available' },
        { name: 'The Departed', genre: 'Crime', ratings: 8.5, status: 'available' },
        { name: 'The Social Network', genre: 'Drama', ratings: 7.7, status: 'available' },
        { name: 'Parasite', genre: 'Thriller', ratings: 8.6, status: 'available' },
        { name: 'The Avengers', genre: 'Action', ratings: 8.0, status: 'available' },
        { name: 'Toy Story', genre: 'Animation', ratings: 8.3, status: 'available' },
        { name: 'Finding Nemo', genre: 'Animation', ratings: 8.1, status: 'available' },
        { name: 'Avatar', genre: 'Sci-Fi', ratings: 7.8, status: 'available' },
        { name: 'Jurassic Park', genre: 'Adventure', ratings: 8.1, status: 'available' },
        { name: 'Star Wars: A New Hope', genre: 'Sci-Fi', ratings: 8.6, status: 'available' },
        { name: 'Back to the Future', genre: 'Adventure', ratings: 8.5, status: 'available' },
        { name: 'The Lord of the Rings: The Fellowship of the Ring', genre: 'Fantasy', ratings: 8.8, status: 'available' },
        { name: 'Harry Potter and the Sorcerer\'s Stone', genre: 'Fantasy', ratings: 7.6, status: 'available' },
        { name: 'The Wizard of Oz', genre: 'Fantasy', ratings: 8.0, status: 'available' },
        { name: 'The Incredibles', genre: 'Animation', ratings: 8.0, status: 'available' },
        { name: 'Spider man: Into the Spider-Verse', genre: 'Animation', ratings: 8.4, status: 'available' },
        { name: 'Coco', genre: 'Animation', ratings: 8.4, status: 'available' },    
        { name: 'Zootopia', genre: 'Animation', ratings: 8.0, status: 'available' },
        { name: 'Moana', genre: 'Animation', ratings: 7.6, status: 'available' },
        { name: 'Frozen', genre: 'Animation', ratings: 7.4, status: 'available' },
        { name: 'Shrek', genre: 'Animation', ratings: 7.9, status: 'available' },
        { name: 'Kung Fu Panda', genre: 'Animation', ratings: 7.6, status: 'available' },
        { name: 'Despicable Me', genre: 'Animation', ratings: 7.6, status: 'available' },
        { name: 'Minions', genre: 'Animation', ratings: 6.4, status: 'available' },
        { name: 'The Secret Life of Pets', genre: 'Animation', ratings: 6.5, status: 'available' },
        { name: 'The office', genre: 'Comedy', ratings: 8.9, status: 'available' },
        { name: 'Friends', genre: 'Comedy', ratings: 8.9, status: 'available' },
        { name: 'Parks and Recreation', genre: 'Comedy', ratings: 8.6, status: 'available' },
        { name: 'Brooklyn Nine-Nine', genre: 'Comedy', ratings: 8.4, status: 'available' },
        { name: 'The Big Bang Theory', genre: 'Comedy', ratings: 8.1, status: 'available' },
        { name: 'How I Met Your Mother', genre: 'Comedy', ratings: 8.3, status: 'available' },
        { name: 'Arrested Development', genre: 'Comedy', ratings: 8.7, status: 'available' },
        { name: 'Community', genre: 'Comedy', ratings: 8.5, status: 'available' },
        { name: 'Scrubs', genre: 'Comedy', ratings: 8.4, status: 'available' },
        { name: 'The Simpsons', genre: 'Animation/Comedy', ratings: 8.7, status: 'available' },
        {name : 'epic movie', genre: 'Comedy', ratings: 2.8, status: 'available'},
        {name : 'Extreme Movie', genre: 'Comedy', ratings: 2.4, status: 'available'},
        {name : 'Disaster Movie', genre: 'Comedy', ratings: 2.0, status: 'available'},
        {name : 'Meet the Spartans', genre: 'Comedy', ratings: 2.0, status: 'available'},
        {name : 'Superhero Movie', genre: 'Comedy', ratings: 2.5, status: 'available'}, 
        {name : 'The Starving Games', genre: 'Comedy', ratings: 2.0, status: 'available'},
        {name : 'The Hangover', genre: 'Comedy', ratings: 7.7, status: 'available'},



    ];
export default Movies;